# Generated by Django 2.1.4 on 2018-12-20 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_url', models.URLField()),
                ('grading_complete', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='RubricField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField(max_length=30)),
                ('weight', models.FloatField()),
                ('value', models.FloatField(default=0.0)),
                ('readable_name', models.CharField(max_length=40)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_fields', to='assignments.Assignment')),
            ],
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_rubric_fields',
            field=models.ManyToManyField(to='assignments.RubricField'),
        ),
    ]
