FROM pattyjogal/code_review_generator

LABEL "com.github.actions.name"="PyLint"
LABEL "com.github.actions.description"="Run the code throught the PyLint linter"
LABEL "com.github.actions.icon"="align-left"
LABEL "com.github.actions.color"="green"

ADD main.sh /main.sh
ENTRYPOINT ["/main.sh"]
